feature : Place Entity
Kpop-Goods/Kg_BE pull request #2
Opened 2023-11-30 16:36 UTC by cdayeon

# Pull Request 제목
feature : Place Entity

## 변경 사항
Place Entity(= class Place) 생성

## 관련 이슈

(해당 Pull Request와 연결된 GitHub 이슈 번호를 기입해주세요.)

## 테스트
- [ v ] API TEST
- [ ] TEST CODE 

DB에 저장되는지 확인을 위해 dto, repository, service, controller 생성
postman 설치 후 json 형식으로 데이터 전송
status 200 확인

## 스크린샷 (선택 사항)

<img width="851" alt="스크린샷 2023-12-01 오전 1 30 33" src="https://github.com/Kpop-Goods/Kg_BE/assets/119835857/f301b757-0bce-4d9a-9a12-1bc05623d03e">

<img width="597" alt="스크린샷 2023-12-01 오전 1 32 01" src="https://github.com/Kpop-Goods/Kg_BE/assets/119835857/17d165de-ce6f-4aa0-9227-487ac5ae7570">

## 기타 정보

(기타 관련 정보나 특별히 언급해야 할 사항이 있다면 여기에 추가하세요.)

---

#### 제출 전 체크리스트
- [ v ] 모든 테스트 케이스가 통과합니다.
- [ v ] 코드는 충분히 문서화되어 있습니다.
- [ ] 모든 커밋은 의미 있는 메시지와 함께 정리되었습니다.
- [ ] 관련 이슈가 링크되었습니다.
- [ ] CI/CD 파이프라인이 성공적으로 완료되었습니다.

2023-12-01 06:35 UTC, kcm02 approved these changes
깔끔하게 만드셨네요 수고 많으셨습니다~

2023-12-02 08:16 UTC, Anthony-Park requested changes
지도의 좌표를  위도 : 경도, latitude : longitude 로 해주십시오. (hardness -> longitude)

2023-12-02 08:16 UTC, Anthony-Park commented on src/main/java/hello/kpop/place/dto/PlaceDto.java
지도의 좌표를  위도 : 경도, latitude : longitude 로 해주십시오. (hardness -> longitude)

2023-12-02 14:54 UTC, cdayeon commented on src/main/java/hello/kpop/place/dto/PlaceDto.java
알려주셔서 감사합니다! hardness -> longitude로 변경하고 Place, PlaceDto, PlaceService 수정완료했습니다!

2023-12-03 05:26 UTC, Anthony-Park approved these changes

2023-12-03 05:27 UTC, Anthony-Park commented on src/main/java/hello/kpop/place/dto/PlaceDto.java
고생하셨습니다!

2023-12-03 09:09 UTC, hwazxcv approved these changes

2023-12-03 14:00 UTC, merged